### ISSUE TITLE
[Feature Request] make migration can insert job

### ISSUE THREAD

**Issue by mix2zeta** [Proteus-tech/mod-ngarn#2]
I need to insert initial some job that will loop itself, for now there are no way to work around it.

**Comment by KayEss** [comment]
Normally the job should add the next job. What is your use case?

**Comment by tleekkul** [comment]
He means to initiate the first job. I think either we have "figure" mechanism or just add it to a migration, I will do it by use tormor migration library to handle this.

**Comment by tleekkul** [comment]
@mix2zeta PR #6 will fix this issue as well

Let's say you want to initiate the first job, you can do it by you can do it by creating a new module for your project (e.g. module `figures`) and then run migrate using `tormor`.

```
Schema
  |- figures
        |-002-initiate-jobs.blue.sql
```

Then you can run
```
SCHEMA_PATH=./Schema tormor -d example_database enable-modules figures
SCHEMA_PATH=./Schema tormor -d example_database migrate
```
